name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: sync dependencies
        run: uv sync --all-extras --frozen

      - name: Run nox
        run: uv run nox
